# Site settings
title: Have a rad summer
email: jeremyellis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is our travelblog
  Hope you like it
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  havearadsummer
source: .
destination: ../_newsite

# Build settings
markdown: kramdown
